[preferences.ui]
album_info_show_description = true
album_info_show_genre = true
album_info_show_narrator = true
album_info_show_year = true
last_used_volume = 0.5

[preferences.podcasts]
jump_backwards_seconds = 30
jump_forward_seconds = 30

[[libraries]]
name = "Music"
path = "/home/joshua/Music"
